apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
  namespace: aul
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: nginx
